### ISSUE TITLE
How to use test.py

### ISSUE THREAD

**Issue by sherpahu** [JusperLee/Looking-to-Listen-at-the-Cocktail-Party#2]
I managed to train anget AVmodel-2p-001.h5
But when I tried to run test.py, I came to a strange bug.
It reads as below,
```
Traceback (most recent call last):
  File "test.py", line 53, in <module>
    av_model = load_model(model_path,custom_objects={'tf':tf})
  File "/home/gz/anaconda3/envs/tf2/lib/python3.7/site-packages/keras/engine/saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)
  File "/home/gz/anaconda3/envs/tf2/lib/python3.7/site-packages/keras/engine/saving.py", line 584, in load_model
    model = _deserialize_model(h5dict, custom_objects, compile)
  File "/home/gz/anaconda3/envs/tf2/lib/python3.7/site-packages/keras/engine/saving.py", line 369, in _deserialize_model
    sample_weight_mode=sample_weight_mode)
  File "/home/gz/anaconda3/envs/tf2/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 75, in symbolic_fn_wrapper
    return func(*args, **kwargs)
  File "/home/gz/anaconda3/envs/tf2/lib/python3.7/site-packages/keras/engine/training.py", line 119, in compile
    self.loss, self.output_names)
  File "/home/gz/anaconda3/envs/tf2/lib/python3.7/site-packages/keras/engine/training_utils.py", line 822, in prepare_loss_functions
    loss_functions = [get_loss_function(loss) for _ in output_names]
  File "/home/gz/anaconda3/envs/tf2/lib/python3.7/site-packages/keras/engine/training_utils.py", line 822, in <listcomp>
    loss_functions = [get_loss_function(loss) for _ in output_names]
  File "/home/gz/anaconda3/envs/tf2/lib/python3.7/site-packages/keras/engine/training_utils.py", line 705, in get_loss_function
    loss_fn = losses.get(loss)
  File "/home/gz/anaconda3/envs/tf2/lib/python3.7/site-packages/keras/losses.py", line 795, in get
    return deserialize(identifier)
  File "/home/gz/anaconda3/envs/tf2/lib/python3.7/site-packages/keras/losses.py", line 776, in deserialize
    printable_module_name='loss function')
  File "/home/gz/anaconda3/envs/tf2/lib/python3.7/site-packages/keras/utils/generic_utils.py", line 167, in deserialize_keras_object
    ':' + function_name)
ValueError: Unknown loss function:loss_func
```
Could you please give me some help?
Since that you are using 百度网盘, I guess we are both Chinese.
So it may be more convenient to discribe it in Chinese.
我训练了几轮后得到了一些h5的权重值，我尝试着跑test.py的时候遇到了上面的报错，我用grep在代码里找了一下发现了叫做loss_func的函数，是不是`av_model = load_model(model_path,custom_objects={'tf':tf})`的问题？
为什么train.py用的是`AV_model = AV.AV_model(people_num)`，而test.py用的却是`av_model = load_model(model_path,custom_objects={'tf':tf})` ?
请问您最后是怎么运行test.py的呢？

**Comment by JusperLee** [comment]
train.py里面AV.AV_model是训练使用，而test里面的load_model是为了加载模型而使用的。

**Comment by JusperLee** [comment]
我直接运行test.py就可以运行代码了
