### ISSUE TITLE
error in test.py file

### ISSUE THREAD

**Issue by 83344rushikesh** [JusperLee/Looking-to-Listen-at-the-Cocktail-Party#4]
@JusperLee hi while running the python3 test.py file I'm getting following error :

python3 test.py
Using TensorFlow backend.
Initialing Parameters......
Loading data ......
2020-03-27 23:11:00.256203: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-03-27 23:11:00.284390: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 1800000000 Hz
2020-03-27 23:11:00.285014: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55b3d04ca750 executing computations on platform Host. Devices:
2020-03-27 23:11:00.285049: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2020-03-27 23:11:00.302032: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
Traceback (most recent call last):
  File "test.py", line 51, in <module>
    av_model = load_model(model_path,custom_objects={'tf':tf})
  File "/home/lenovo/.local/lib/python3.6/site-packages/keras/engine/saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)
  File "/home/lenovo/.local/lib/python3.6/site-packages/keras/engine/saving.py", line 584, in load_model
    model = _deserialize_model(h5dict, custom_objects, compile)
  File "/home/lenovo/.local/lib/python3.6/site-packages/keras/engine/saving.py", line 369, in _deserialize_model
    sample_weight_mode=sample_weight_mode)
  File "/home/lenovo/.local/lib/python3.6/site-packages/keras/engine/training.py", line 119, in compile
    self.loss, self.output_names)
  File "/home/lenovo/.local/lib/python3.6/site-packages/keras/engine/training_utils.py", line 822, in prepare_loss_functions
    loss_functions = [get_loss_function(loss) for _ in output_names]
  File "/home/lenovo/.local/lib/python3.6/site-packages/keras/engine/training_utils.py", line 822, in <listcomp>
    loss_functions = [get_loss_function(loss) for _ in output_names]
  File "/home/lenovo/.local/lib/python3.6/site-packages/keras/engine/training_utils.py", line 705, in get_loss_function
    loss_fn = losses.get(loss)
  File "/home/lenovo/.local/lib/python3.6/site-packages/keras/losses.py", line 795, in get
    return deserialize(identifier)
  File "/home/lenovo/.local/lib/python3.6/site-packages/keras/losses.py", line 776, in deserialize
    printable_module_name='loss function')
  File "/home/lenovo/.local/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 167, in deserialize_keras_object
    ':' + function_name)
ValueError: Unknown loss function:loss_func

Can you please help it out?

**Comment by JusperLee** [comment]
I think there is something wrong with my test.py header file, I don't know if you have modified it.

import sys
sys.path.append ('./ model / model')
sys.path.append ('./ model / utils')
from keras.models import load_model
from option import ModelMGPU
import os
import scipy.io.wavfile as wavfile
import numpy as np
import utils
import tensorflow as tf

**Comment by 83344rushikesh** [comment]
@JusperLee The code is exactly same which you have given in your repo. 
Can you please share your pre-trained model ?

**Comment by JusperLee** [comment]
The above code was just modified. I'm so sorry. The Pre-train model was not saved due to my computer damage.

**Comment by 83344rushikesh** [comment]
@JusperLee I have checked the updated code. It is still giving the same error (ValueError: Unknown loss function:loss_func).

**Comment by JusperLee** [comment]
The solutions may be as follows:
1. Do you use multiple GPUs for testing or training. If a pre-trained model is used for multiple GPUs, it cannot be trained or tested with one GPU in the future. (Need to change the parameter on line 31 to NUM_GPU = N, where N is the number of GPUs)
2. Maybe the pre-trained model uses a different custom loss function. Try changing line 11 from model_loss import audio_discriminate_loss2 as audio_loss in AV_train.py to model_loss import audio_discriminate_loss as audio_loss.
3. Keras is not good at multiprocessing. It is not recommended to use it

**Comment by 83344rushikesh** [comment]
@JusperLee thanks. I will check this.

**Comment by 83344rushikesh** [comment]
@JusperLee There is some custom functions for calculating the loss. I have added that functions to the inbuild losses.py file but it is still giving the same error. Can you please share your audio-only pre-trained model? I think that will surely help to solve the problem.

**Comment by JusperLee** [comment]
I looked for it and I don't have an audio-only pre-trained model. Now only AVModel. Since this project was not able to get good results, I did not go into further research.

link: https://pan.baidu.com/s/19rcXmo4AuxSCIORTPnaFEw  password:  djb6

**Comment by 83344rushikesh** [comment]
@JusperLee is it the audio-visual pre-trained model?

**Comment by JusperLee** [comment]
Yes.

**Comment by 83344rushikesh** [comment]
@JusperLee It is in chinese language.

**Comment by 83344rushikesh** [comment]
@JusperLee can you upload these pre-trained model on you repo?

**Comment by JusperLee** [comment]
this is google driver's link: https://drive.google.com/open?id=1bnvksxwGBfFKMN90FIib9EPgPpQT6DQb

**Comment by 83344rushikesh** [comment]
@JusperLee Thanks sir.
What was your environment of system while training the model?

**Comment by 83344rushikesh** [comment]
@JusperLee Sir, can you please explain how to use this model to test it on video to isolate the speakers?

**Comment by JusperLee** [comment]
Environment: 
Python3.7
TensorFlow 2.0.0
Keras 2.3.1
librosa 0.7.0
youtube-dl(https://github.com/ytdl-org/youtube-dl)(Any version)
ffmpeg(https://www.ffmpeg.org/)（Any version）

test step:
First you preprocess the video. Extract the audio signal of the video, and then extract the face from the video frame. This part is similar to the data preparation stage, you can refer to the steps in the data directory. Finally, modify the contents of test.py and run the file.
